openapi: 3.0.0
info:
  title: Nuts Demo EHR API
  version: 1.0.0

paths:
  # Password authentication
  /web/auth-passwd:
    post:
      description: Authenticate using password credential. If successful an authenticated session is created and returned.
      operationId: authenticateWithPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordAuthenticateRequest"
      responses:
        '204':
          description: Authentication successful.
        '403':
          description: Invalid credentials
  # IRMA authentication
  /web/auth/session:
    post:
      operationId: createSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IRMAAuthenticationRequest"
      responses:
        '200':
          description: A session was succesfully created
          content:
            application/json:
              schema:
                type: object
  /web/auth/session/{sessionToken}/result:
    parameters:
      - name: sessionToken
        in: path
        description: IRMA session ID
        required: true
        schema:
          type: string
    get:
      operationId: sessionResult
      responses:
        '200':
          description: Session result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionToken"

  # General authentication endpoints
  /web/private:
    get:
      description: Checks whether the current session is valid. If not, the client should authenticate before calling other API operations.
      operationId: checkSession
      responses:
        '204':
          description: The session is valid.
        '400':
          description: The session is invalid.

  /web/customers:
    get:
      operationId: listCustomers
      responses:
        200:
          description: returns a list of customers as configured in the customers.json file
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
  /web/customers/{id}:
    parameters:
      - name: id
        in: path
        description: internal customer ID
        required: true
        schema:
          type: string
    get:
      operationId: getCustomer
      responses:
        200:
          description: returns the specified customer as configured in the customers.json file
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          description: customer not found

components:
  schemas:
    Customer:
      type: object
      description: A customer object
      required:
        - id
        - name
        - active
      properties:
        id:
          type: string
          description: The internal customer ID.
          example: "C12"
        did:
          type: string
          description: The customer DID.
          example:
            "did:nuts:123"
        name:
          type: string
          description: Internal name for this customer.
        city:
          type: string
          description: Locality for this customer.
        domain:
          type: string
          description: The email domain of the care providers employees, required for logging in.
        active:
          type: boolean
          description: If a VC has been issued for this customer.
    SessionToken:
      type: object
      description: Result of a signing session.
      required:
        - token
      properties:
        token:
          type: string
          description: the result from a signing session. It's a base64 encoded Verifiable Presentation
    IRMAAuthenticationRequest:
      required:
        - customerID
      properties:
        customerID:
          description: Internal ID of the customer for which is being logged in
          type: string
          example: 1
    PasswordAuthenticateRequest:
      required:
        - customerID
        - password
      properties:
        customerID:
          description: Internal ID of the customer for which is being logged in
          type: string
          example: 1
        password:
          type: string
